/**
 * English — the fallback locale. Every key present in ko.ts must exist here,
 * because a missing key in the fallback renders the raw key in the UI.
 * `tests/localization.test.ts` enforces parity between the two bundles.
 */

export const en: Record<string, string> = {
  'app.title': 'PROJECT TITAN',
  'common.ok': 'OK',
  'common.cancel': 'Cancel',
  'common.back': 'Back',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.loading': 'Loading...',
  'common.retry': 'Retry',
  'common.equip': 'Equip',
  'common.equipped': 'Equipped',
  'common.unequip': 'Unequip',
  'common.buy': 'Buy',
  'common.owned': 'Owned',
  'common.locked': 'Locked',
  'common.level_required': 'Requires level {level}',
  'common.free': 'Free',
  'common.search': 'Search',
  'common.all': 'All',
  'common.none': 'None',
  'common.save': 'Save',
  'common.reset': 'Reset',
  'common.apply': 'Apply',
  'common.next': 'Next',
  'common.previous': 'Previous',
  'common.claim': 'Claim',
  'common.claimed': 'Claimed',
  'common.progress': 'Progress',
  'common.complete': 'Complete',
  'common.seconds': '{count}s',
  'common.minutes': '{count}m',

  'boot.initializing': 'Initializing systems',
  'boot.loading_assets': 'Loading assets',
  'boot.connecting': 'Connecting to server',
  'boot.loading_profile': 'Loading profile',
  'boot.building_world': 'Building world',
  'boot.ready': 'Ready',
  'boot.tip': 'Tip',

  'menu.play': 'Play',
  'menu.lobby': 'Lobby',
  'menu.inventory': 'Inventory',
  'menu.shop': 'Store',
  'menu.loadout': 'Loadout',
  'menu.characters': 'Operators',
  'menu.quests': 'Contracts',
  'menu.rank': 'Rank',
  'menu.season': 'Season',
  'menu.leaderboard': 'Leaderboard',
  'menu.settings': 'Settings',
  'menu.profile': 'Profile',
  'menu.news': 'News',
  'menu.social': 'Social',
  'menu.quit': 'Quit',
  'menu.tutorial': 'Tutorial',

  'login.title': 'Operator Sign-In',
  'login.name_label': 'Operator name',
  'login.name_placeholder': 'Enter a name',
  'login.enter': 'Enter',
  'login.guest': 'Continue as guest',
  'login.name_too_short': 'Name must be at least 2 characters.',
  'login.name_too_long': 'Name must be 16 characters or fewer.',
  'login.name_invalid': 'That name contains unsupported characters.',
  'login.returning': 'Welcome back, Operator {name}.',

  'match.searching': 'Searching for a match',
  'match.found': 'Match found',
  'match.joining': 'Joining',
  'match.cancel_search': 'Cancel search',
  'match.queue_time': 'Queued {time}',
  'match.players_found': '{current} / {total} players',
  'match.warmup': 'Warmup',
  'match.starting_in': 'Starting in {count}',
  'match.round': 'Round {current}',
  'match.round_start': 'Round start',
  'match.round_end': 'Round over',
  'match.victory': 'Victory',
  'match.defeat': 'Defeat',
  'match.draw': 'Draw',
  'match.match_end': 'Match over',
  'match.overtime': 'Overtime',
  'match.spectating': 'Spectating {name}',
  'match.respawning': 'Respawning in {count}',
  'match.eliminated': 'Eliminated',
  'match.waiting_players': 'Waiting for players',
  'match.team_alpha': 'Alpha',
  'match.team_bravo': 'Bravo',
  'match.score': 'Score',
  'match.leave': 'Leave match',
  'match.leave_confirm': 'Leave the match? You may forfeit pending rewards.',

  'hud.health': 'Health',
  'hud.shield': 'Shield',
  'hud.ammo': 'Ammo',
  'hud.stamina': 'Stamina',
  'hud.reloading': 'Reloading',
  'hud.no_ammo': 'Out of ammo',
  'hud.skill_ready': 'Ability ready',
  'hud.spawn_protection': 'Spawn protection',
  'hud.objective_capturing': 'Capturing',
  'hud.objective_contested': 'Contested',
  'hud.objective_captured': '{team} captured',
  'hud.killstreak': '{count} kill streak',
  'hud.doublekill': 'Double kill',
  'hud.triplekill': 'Triple kill',
  'hud.multikill': 'Multi kill x{count}',
  'hud.headshot': 'Headshot',
  'hud.first_blood': 'First blood',
  'hud.assist': 'Assist',
  'hud.out_of_bounds': 'Return to the battlefield {count}',
  'hud.interact': 'Press {key} to interact',
  'hud.enter_vehicle': 'Press {key} to enter',
  'hud.exit_vehicle': 'Press {key} to exit',
  'hud.press_to_talk': 'Press {key} to talk',

  'killfeed.killed': 'eliminated',
  'killfeed.suicide': 'self-eliminated',
  'killfeed.fall': 'fell',
  'killfeed.environment': 'environment',
  'killfeed.vehicle': 'vehicle',

  'result.title': 'Match Results',
  'result.mvp': 'MVP',
  'result.kills': 'Kills',
  'result.deaths': 'Deaths',
  'result.assists': 'Assists',
  'result.kd': 'K/D',
  'result.damage': 'Damage',
  'result.headshots': 'Headshots',
  'result.score': 'Score',
  'result.accuracy': 'Accuracy',
  'result.best_streak': 'Best streak',
  'result.xp_earned': 'XP earned',
  'result.coins_earned': 'Coins earned',
  'result.rank_change': 'Rank change',
  'result.continue': 'Continue',
  'result.rematch': 'Play again',
  'result.time_played': 'Time played',

  'inventory.title': 'Inventory',
  'inventory.category': 'Category',
  'inventory.rarity': 'Rarity',
  'inventory.sort': 'Sort',
  'inventory.sort_rarity': 'By rarity',
  'inventory.sort_name': 'By name',
  'inventory.sort_recent': 'Newest',
  'inventory.empty': 'Nothing matches that filter.',
  'inventory.empty_hint':
    'Buy skins and supply crates in the store, or earn them from contracts and rank rewards.',
  'inventory.preview': 'Preview',
  'inventory.item_count': '{count} owned',

  'shop.title': 'Store',
  'shop.section.featured': 'Featured',
  'shop.section.daily': 'Daily',
  'shop.section.weapons': 'Weapons',
  'shop.section.attachments': 'Attachments',
  'shop.section.characters': 'Operators',
  'shop.section.cosmetics': 'Cosmetics',
  'shop.section.crates': 'Supply crates',
  'shop.section.event': 'Event',
  'shop.refresh_in': 'Refreshes in {time}',
  'shop.purchase_confirm': 'Buy {item} for {price} {currency}?',
  'shop.purchase_success': 'Purchased {item}',
  'shop.discount': '{percent}% off',
  'shop.balance': 'Balance',

  'currency.coins': 'Coins',
  'currency.cores': 'Cores',

  'crate.open': 'Open',
  'crate.opening': 'Opening',
  'crate.rates_title': 'Drop rates',
  'crate.rates_note': 'These are the exact rates the server rolls against.',
  'crate.duplicate': 'Duplicate — converted to {coins} coins',
  'crate.pity': 'Guaranteed {rarity} or better within {count} opens',
  'crate.result_title': 'You received',

  'rarity.common': 'Common',
  'rarity.uncommon': 'Uncommon',
  'rarity.rare': 'Rare',
  'rarity.epic': 'Epic',
  'rarity.legendary': 'Legendary',
  'rarity.mythic': 'Mythic',

  'quest.title': 'Contracts',
  'quest.daily': 'Daily',
  'quest.weekly': 'Weekly',
  'quest.story': 'Operations',
  'quest.secret': 'Classified',
  'quest.secret_undiscovered': '???',
  'quest.resets_in': 'Resets in {time}',
  'quest.completed': 'Completed',
  'quest.claim_reward': 'Claim reward',
  'quest.new_available': 'New contracts available',
  'quest.progress_updated': '{name} ({current}/{total})',

  'objective.kill': 'Eliminate {count} enemies',
  'objective.kill_class': 'Eliminate {count} with {target}',
  'objective.headshot': 'Land {count} headshots',
  'objective.assist': 'Earn {count} assists',
  'objective.damage': 'Deal {count} damage',
  'objective.win': 'Win {count} matches',
  'objective.play': 'Play {count} matches',
  'objective.capture': 'Capture {count} objectives',
  'objective.use_skill': 'Use your ability {count} times',
  'objective.skill_kill': 'Eliminate {count} with an ability',
  'objective.streak': 'Reach a {threshold} kill streak',
  'objective.long_shot': 'Get {count} eliminations from over {threshold}m',
  'objective.visit': 'Discover a location',
  'objective.talk': 'Speak to an operator',
  'objective.collect': 'Collect {count} items',
  'objective.level': 'Reach level {count}',
  'objective.rank': 'Reach {target} rank',
  'objective.terminal': 'Activate the terminal',
  'objective.panel': 'Find the hidden panel',
  'objective.find_vault': 'Enter the sealed vault',
  'objective.find_backroom': 'Enter the back room',
  'objective.vehicle_distance': 'Drive {count}m',

  'progress.level': 'Level {level}',
  'progress.level_up': 'Level up!',
  'progress.xp': '{current} / {total} XP',
  'progress.max_level': 'Max level',
  'progress.reward_unlocked': 'Unlocked: {name}',
  'rank.title': 'Rank',
  'rank.unranked': 'Unranked',
  'rank.iron': 'Iron',
  'rank.bronze': 'Bronze',
  'rank.silver': 'Silver',
  'rank.gold': 'Gold',
  'rank.platinum': 'Platinum',
  'rank.diamond': 'Diamond',
  'rank.ascendant': 'Ascendant',
  'rank.titan': 'Titan',
  'rank.division': '{tier} {division}',
  'rank.promoted': 'Promoted!',
  'rank.demoted': 'Demoted',
  'rank.points': '{points} RP',
  'rank.placement': 'Placement {current}/{total}',

  'season.title': 'Season',
  'season.level': 'Season level {level}',
  'season.ends_in': 'Ends in {time}',
  'season.premium_locked': 'Premium track locked',
  'season.s1.name': 'Season 1: First Signal',
  'season.s1.desc': 'The opening operational season of the Titan programme.',

  'login_reward.title': 'Daily Login',
  'login_reward.streak': '{count} day streak',
  'login_reward.day': 'Day {day}',
  'login_reward.today': "Today's reward",
  'login_reward.missed': 'Your streak has reset.',

  'achievement.title': 'Achievements',
  'achievement.unlocked': 'Achievement unlocked: {name}',
  'achievement.hidden': 'Hidden achievement',
  'achievement.progress': '{current} / {total}',

  'party.title': 'Party',
  'party.create': 'Create party',
  'party.invite': 'Invite',
  'party.leave': 'Leave party',
  'party.disband': 'Disband party',
  'party.leader': 'Leader',
  'party.ready': 'Ready',
  'party.not_ready': 'Not ready',
  'party.code': 'Party code: {code}',
  'party.join_code': 'Join by code',
  'party.full': 'That party is full.',
  'party.invited': 'Invited {name}.',
  'party.joined': '{name} joined.',
  'party.left': '{name} left.',
  'party.member_count': '{current}/{max}',

  'social.friends': 'Friends',
  'social.add_friend': 'Add friend',
  'social.remove_friend': 'Remove friend',
  'social.online': 'Online',
  'social.offline': 'Offline',
  'social.in_match': 'In a match',
  'social.in_lobby': 'In the lobby',
  'social.block': 'Block',
  'social.unblock': 'Unblock',
  'social.mute': 'Mute',
  'social.report': 'Report',
  'social.blocked_list': 'Blocked players',

  'report.title': 'Report player',
  'report.reason': 'Reason',
  'report.reason.cheating': 'Cheating',
  'report.reason.abuse': 'Abusive behaviour',
  'report.reason.exploit': 'Exploiting',
  'report.reason.other': 'Other',
  'report.details': 'Details (optional)',
  'report.submit': 'Submit report',
  'report.submitted': 'Report received. It will be reviewed.',
  'report.privacy_note': 'Reports include only the minimum information needed for review.',

  'spectate.title': 'Spectate',
  'spectate.next': 'Next player',
  'spectate.prev': 'Previous player',
  'spectate.free_cam': 'Free camera',
  'spectate.follow': 'Follow',

  'settings.title': 'Settings',
  'settings.tab.graphics': 'Graphics',
  'settings.tab.audio': 'Audio',
  'settings.tab.controls': 'Controls',
  'settings.tab.gameplay': 'Gameplay',
  'settings.tab.accessibility': 'Accessibility',
  'settings.tab.language': 'Language',

  'settings.graphics.preset': 'Quality preset',
  'settings.graphics.preset.low': 'Low',
  'settings.graphics.preset.medium': 'Medium',
  'settings.graphics.preset.high': 'High',
  'settings.graphics.preset.custom': 'Custom',
  'settings.graphics.resolution_scale': 'Resolution scale',
  'settings.graphics.fps_limit': 'FPS limit',
  'settings.graphics.vsync': 'VSync',
  'settings.graphics.shadows': 'Shadows',
  'settings.graphics.shadow_quality': 'Shadow quality',
  'settings.graphics.postprocessing': 'Post-processing',
  'settings.graphics.bloom': 'Bloom',
  'settings.graphics.vfx_quality': 'VFX quality',
  'settings.graphics.particle_density': 'Particle density',
  'settings.graphics.view_distance': 'View distance',
  'settings.graphics.anisotropic': 'Anisotropic filtering',
  'settings.graphics.antialiasing': 'Anti-aliasing',
  'settings.graphics.detail_props': 'Detail props',
  'settings.graphics.reflections': 'Reflections',
  'settings.graphics.low_spec_note':
    'Even on Low, enemies, ammo and objectives stay clearly readable.',

  'settings.audio.master': 'Master',
  'settings.audio.music': 'Music',
  'settings.audio.sfx': 'Effects',
  'settings.audio.voice': 'Voice',
  'settings.audio.ui': 'Interface',
  'settings.audio.ambience': 'Ambience',
  'settings.audio.spatial': 'Spatial audio',

  'settings.controls.sensitivity': 'Mouse sensitivity',
  'settings.controls.ads_sensitivity': 'ADS sensitivity multiplier',
  'settings.controls.invert_y': 'Invert Y axis',
  'settings.controls.toggle_ads': 'Toggle aim',
  'settings.controls.toggle_crouch': 'Toggle crouch',
  'settings.controls.toggle_sprint': 'Toggle sprint',
  'settings.controls.keybinds': 'Key bindings',
  'settings.controls.rebind': 'Press a key for {action}',
  'settings.controls.gamepad': 'Gamepad',
  'settings.controls.gamepad_sensitivity': 'Gamepad sensitivity',
  'settings.controls.touch_layout': 'Touch layout',
  'settings.controls.reset_defaults': 'Reset to defaults',

  'settings.gameplay.fov': 'Field of view',
  'settings.gameplay.crosshair': 'Crosshair',
  'settings.gameplay.crosshair_color': 'Crosshair colour',
  'settings.gameplay.crosshair_size': 'Crosshair size',
  'settings.gameplay.crosshair_gap': 'Crosshair gap',
  'settings.gameplay.crosshair_dot': 'Centre dot',
  'settings.gameplay.damage_numbers': 'Damage numbers',
  'settings.gameplay.hitmarkers': 'Hitmarkers',
  'settings.gameplay.killfeed': 'Kill feed',
  'settings.gameplay.minimap_rotate': 'Rotate minimap',
  'settings.gameplay.show_fps': 'Show FPS',
  'settings.gameplay.show_ping': 'Show ping',

  'settings.accessibility.camera_shake': 'Camera shake',
  'settings.accessibility.motion_reduction': 'Reduce motion',
  'settings.accessibility.text_size': 'Text size',
  'settings.accessibility.subtitles': 'Subtitles',
  'settings.accessibility.subtitle_size': 'Subtitle size',
  'settings.accessibility.colorblind': 'Colourblind mode',
  'settings.accessibility.colorblind.none': 'Off',
  'settings.accessibility.colorblind.protanopia': 'Protanopia',
  'settings.accessibility.colorblind.deuteranopia': 'Deuteranopia',
  'settings.accessibility.colorblind.tritanopia': 'Tritanopia',
  'settings.accessibility.high_contrast': 'High contrast UI',
  'settings.accessibility.flash_reduction': 'Reduce flashing',
  'settings.accessibility.hold_to_ads': 'Aim behaviour',
  'settings.accessibility.audio_cues': 'Visual audio cues',

  'settings.language.title': 'Language',
  'settings.language.planned': 'Planned',
  'locale.ko': 'Korean',
  'locale.en': 'English',

  'network.ping': '{ms}ms',
  'network.status.excellent': 'Excellent',
  'network.status.good': 'Good',
  'network.status.fair': 'Fair',
  'network.status.poor': 'Poor',
  'network.disconnected': 'Connection lost',
  'network.reconnecting': 'Reconnecting... ({attempt}/{max})',
  'network.reconnected': 'Reconnected',
  'network.reconnect_failed': 'Could not reconnect.',
  'network.session_restored': 'Match state restored.',
  'network.server_status': 'Server status',

  'notify.item_received': 'Received {name}',
  'notify.reward_received': 'Reward received',
  'notify.level_up': 'Reached level {level}',
  'notify.rank_up': 'Promoted to {rank}',
  'notify.quest_complete': 'Contract complete: {name}',
  'notify.achievement': 'Achievement: {name}',
  'notify.friend_online': '{name} is online',
  'notify.party_invite': '{name} invited you to a party',
  'notify.event_started': 'Event started: {name}',
  'notify.system': 'Notice',

  'error.unknown': 'Something went wrong. Please try again shortly.',
  'error.validation': 'Please check what you entered.',
  'error.not_found': "That item couldn't be found.",
  'error.forbidden': "You don't have permission to do that.",
  'error.rate_limited': 'Too many requests. Please wait a moment.',
  'error.insufficient_funds': "You don't have enough currency.",
  'error.already_owned': 'You already own that.',
  'error.not_owned': "You don't own that.",
  'error.level_requirement': 'Requires level {level}.',
  'error.unavailable': 'Not available right now.',
  'error.conflict': 'This changed elsewhere. Refresh and try again.',
  'error.storage': 'Saving failed. Your progress was kept locally.',
  'error.network': 'Cannot reach the network.',
  'error.match_full': 'That match is full.',
  'error.party_full': 'That party is full.',
  'error.not_party_leader': 'Only the party leader can do that.',
  'error.asset_missing': 'An asset failed to load; a placeholder is being used.',
  'error.payment_unavailable': 'This build ships without payment support.',
  'error.protocol_mismatch': 'Your client version differs from the server. Please refresh.',

  'weapon.tr9_sentinel.name': 'TR-9 Sentinel',
  'weapon.tr9_sentinel.desc': 'Balanced service rifle. The most dependable option at mid range.',
  'weapon.ak_ridgeline.name': 'AK Ridgeline',
  'weapon.ak_ridgeline.desc': 'Heavy hitting, heavy recoil. Rewards short controlled bursts.',
  'weapon.vx3_lattice.name': 'VX-3 Lattice',
  'weapon.vx3_lattice.desc': 'Precision three-round burst. A missed burst costs you the fight.',
  'weapon.vp4_hornet.name': 'VP-4 Hornet',
  'weapon.vp4_hornet.desc': 'Best-in-class up close. Falls apart past 30m.',
  'weapon.sk2_cinder.name': 'SK-2 Cinder',
  'weapon.sk2_cinder.desc': 'A controllable SMG with a small magazine.',
  'weapon.br12_fracture.name': 'BR-12 Fracture',
  'weapon.br12_fracture.desc': 'One-shot potential point blank. Helpless in the open.',
  'weapon.mk7_nightfall.name': 'MK-7 Nightfall',
  'weapon.mk7_nightfall.desc': 'Headshots kill at any range. Little answer to a rusher.',
  'weapon.dm3_verdict.name': 'DM-3 Verdict',
  'weapon.dm3_verdict.desc': 'Semi-auto marksman rifle. Two rounds is enough.',
  'weapon.sp1_ember.name': 'SP-1 Ember',
  'weapon.sp1_ember.desc': 'Fastest swap in the game. The answer to an empty magazine.',
  'weapon.rift_blade.name': 'Rift Blade',
  'weapon.rift_blade.desc': 'Top movement speed and a two-hit kill. Closing distance is the whole job.',
  'weapon.arc9_tempest.name': 'ARC-9 Tempest',
  'weapon.arc9_tempest.desc': 'Energy bolts with no falloff. Slow travel — you must lead your shots.',

  'weapon.class.assault_rifle': 'Assault Rifle',
  'weapon.class.smg': 'SMG',
  'weapon.class.shotgun': 'Shotgun',
  'weapon.class.sniper': 'Sniper',
  'weapon.class.marksman': 'Marksman',
  'weapon.class.pistol': 'Pistol',
  'weapon.class.melee': 'Melee',
  'weapon.class.special': 'Special',

  'weapon.stat.damage': 'Damage',
  'weapon.stat.fire_rate': 'Fire rate',
  'weapon.stat.range': 'Range',
  'weapon.stat.accuracy': 'Accuracy',
  'weapon.stat.recoil': 'Recoil control',
  'weapon.stat.mobility': 'Mobility',
  'weapon.stat.magazine': 'Magazine',
  'weapon.stat.reload': 'Reload',
  'weapon.stat.ads_speed': 'ADS speed',
  'weapon.stat.headshot': 'Headshot multiplier',

  'attachment.slot.optic': 'Optic',
  'attachment.slot.barrel': 'Barrel',
  'attachment.slot.grip': 'Grip',
  'attachment.slot.magazine': 'Magazine',
  'attachment.slot.stock': 'Stock',
  'attachment.slot.special': 'Special',
  'attachment.optic_reflex.name': 'Reflex Sight',
  'attachment.optic_reflex.desc': 'Cleaner sight picture, slightly slower to aim.',
  'attachment.optic_longscope.name': 'Long Scope',
  'attachment.optic_longscope.desc': 'Heavy zoom at the cost of ADS speed and mobility.',
  'attachment.optic_holo_wide.name': 'Wide Holo',
  'attachment.optic_holo_wide.desc': 'Fast aim and a wide view; a looser cone.',
  'attachment.barrel_long.name': 'Extended Barrel',
  'attachment.barrel_long.desc': 'More effective range; the weapon handles slower.',
  'attachment.barrel_suppressor.name': 'Suppressor',
  'attachment.barrel_suppressor.desc': 'No minimap reveal when firing. Less damage and range.',
  'attachment.barrel_compensator.name': 'Compensator',
  'attachment.barrel_compensator.desc': 'Less vertical climb, more horizontal wander.',
  'attachment.grip_vertical.name': 'Vertical Grip',
  'attachment.grip_vertical.desc': 'Better recoil control; slower strafe while aiming.',
  'attachment.grip_light.name': 'Light Grip',
  'attachment.grip_light.desc': 'Quicker to aim and move; harder to hold on target.',
  'attachment.mag_extended.name': 'Extended Magazine',
  'attachment.mag_extended.desc': '+10 rounds, noticeably longer reload.',
  'attachment.mag_quickdraw.name': 'Quickdraw Magazine',
  'attachment.mag_quickdraw.desc': 'Much faster reloads, 4 fewer rounds.',
  'attachment.stock_heavy.name': 'Heavy Stock',
  'attachment.stock_heavy.desc': 'More stability, less movement speed.',
  'attachment.stock_skeletal.name': 'Skeletal Stock',
  'attachment.stock_skeletal.desc': 'More mobility, harder recoil.',
  'attachment.special_ported_chamber.name': 'Ported Chamber',
  'attachment.special_ported_chamber.desc': 'Higher fire rate, lower damage per shot.',
  'attachment.special_focus_coil.name': 'Focus Coil',
  'attachment.special_focus_coil.desc': 'Very tight cone; slow to bring up.',

  'character.vanguard.name': 'Vanguard',
  'character.vanguard.desc': 'The baseline operator — every stat sits at 1.0.',
  'character.specter.name': 'Specter',
  'character.specter.desc': 'Faster but frailer. Built to flank, not to duel.',
  'character.warden.name': 'Warden',
  'character.warden.desc': 'Extra shield, clearly slower. Holds ground.',
  'character.surveyor.name': 'Surveyor',
  'character.surveyor.desc': 'Information operator. The scan is the value.',
  'character.forge.name': 'Forge',
  'character.forge.desc': 'Support. Keeps the team standing.',

  'skill.pulse_dash.name': 'Pulse Dash',
  'skill.pulse_dash.desc': 'Burst a short distance. You cannot steer mid-dash.',
  'skill.pulse_dash.up1': 'Cooldown reduced 10%',
  'skill.pulse_dash.up2': 'Impulse increased 10%',
  'skill.bulwark.name': 'Bulwark',
  'skill.bulwark.desc': 'Deploy a barrier. It blocks your own fire too.',
  'skill.bulwark.up1': 'Barrier health +15%',
  'skill.bulwark.up2': 'Duration +20%',
  'skill.scan_pulse.name': 'Scan Pulse',
  'skill.scan_pulse.desc': 'Briefly reveals nearby enemies. It announces you too.',
  'skill.scan_pulse.up1': 'Radius +15%',
  'skill.scan_pulse.up2': 'Cooldown -15%',
  'skill.ion_charge.name': 'Ion Charge',
  'skill.ion_charge.desc': 'Throw an explosive charge. It cannot kill on its own.',
  'skill.ion_charge.up1': 'Blast radius +12%',
  'skill.ion_charge.up2': 'Fuse 20% shorter',
  'skill.phase_veil.name': 'Phase Veil',
  'skill.phase_veil.desc': 'Distort your outline. You cannot fire while active.',
  'skill.phase_veil.up1': 'Duration +15%',
  'skill.phase_veil.up2': 'Stronger concealment',
  'skill.field_repair.name': 'Field Repair',
  'skill.field_repair.desc': 'Heal yourself and nearby allies. Interrupted by damage.',
  'skill.field_repair.up1': 'Healing +15%',
  'skill.field_repair.up2': 'Radius +20%',
  'skill.category.offense': 'Offense',
  'skill.category.defense': 'Defense',
  'skill.category.mobility': 'Mobility',
  'skill.category.utility': 'Utility',

  'vehicle.scout_buggy.name': 'Scout Buggy',
  'vehicle.scout_buggy.desc': 'Fast, fragile recon vehicle. You hear it long before you see it.',

  'map.foundry_reach.name': 'Foundry Reach',
  'map.foundry_reach.desc':
    'A smelting complex at dusk. Long west lane, vertical centre, tight east warehouses.',
  'map.foundry_reach.obj.yard': 'Container Yard',
  'map.foundry_reach.obj.foundry': 'Foundry',
  'map.foundry_reach.obj.depot': 'Depot',
  'map.neon_quarter.name': 'Neon Quarter',
  'map.neon_quarter.desc': 'A rain-soaked night market. Cross the plaza, or take the long way.',
  'map.neon_quarter.obj.plaza': 'Central Plaza',
  'map.neon_quarter.obj.west_row': 'West Row',
  'map.neon_quarter.obj.east_row': 'East Row',
  'map.titan_hub.name': 'Titan Hub',
  'map.titan_hub.desc': 'Staging area.',
  'map.zone.west_yard': 'West Yard',
  'map.zone.foundry_hall': 'Foundry Hall',
  'map.zone.east_warehouse': 'East Warehouse',
  'map.zone.rooftops': 'Rooftops',
  'map.zone.tunnel': 'Maintenance Tunnel',
  'map.zone.vault': 'Sealed Vault',
  'map.zone.plaza': 'Plaza',
  'map.zone.walkway': 'Elevated Walkway',
  'map.zone.shops_west': 'West Shops',
  'map.zone.shops_east': 'East Shops',
  'map.zone.alley': 'Flooded Alley',
  'map.zone.backroom': 'Back Room',
  'map.zone.concourse': 'Concourse',
  'map.zone.range': 'Firing Range',
  'map.zone.mezzanine': 'Mezzanine',

  'mode.tdm.name': 'Team Deathmatch',
  'mode.tdm.desc': 'First team to the score limit wins.',
  'mode.ffa.name': 'Free For All',
  'mode.ffa.desc': 'Everyone is a target.',
  'mode.objective.name': 'Objective',
  'mode.objective.desc': 'Capture and hold points to score.',
  'mode.elimination.name': 'Elimination',
  'mode.elimination.desc': 'No respawns. Be the last team standing.',
  'mode.ranked.name': 'Ranked',
  'mode.ranked.desc': 'Compete with rank points on the line.',

  'npc.quartermaster.name': 'Quartermaster Ren',
  'npc.quartermaster.role': 'Supply',
  'npc.armorer.name': 'Armorer Kyle',
  'npc.armorer.role': 'Weapon maintenance',
  'npc.dispatcher.name': 'Dispatcher Iseo',
  'npc.dispatcher.role': 'Operations',
  'npc.instructor.name': 'Instructor Doha',
  'npc.instructor.role': 'Training',
  'npc.archivist.name': 'The Archivist',
  'npc.archivist.role': '???',

  'dialogue.quartermaster.root': 'Need something, Operator? Stock is good.',
  'dialogue.quartermaster.gear': 'The best gear is the gear that fits the fight.',
  'dialogue.quartermaster.attachments': 'Nothing on that rack is free. Gain something, lose something.',
  'dialogue.armorer.root': "I'll handle the maintenance. What are you taking out?",
  'dialogue.armorer.balance': 'Every weapon has a weakness. Knowing it is the skill.',
  'dialogue.dispatcher.root': 'Contract board is updated. Take a look.',
  'dialogue.dispatcher.modes': 'Elimination gives you one life. Think before you push.',
  'dialogue.instructor.root': "Back to basics. Until your body remembers it.",
  'dialogue.instructor.movement': 'Crouch while sprinting to slide. Use it around corners.',
  'dialogue.instructor.slide': 'Jump out of a slide and you carry the speed further.',
  'dialogue.archivist.root': '...',
  'dialogue.archivist.signal': 'So you found the signal. Most never do.',
  'dialogue.archivist.more': 'Two more places are sealed. Find them, then come back.',

  'dialogue.opt.browse_shop': 'Show me the store',
  'dialogue.opt.ask_about_gear': 'Ask about gear',
  'dialogue.opt.ask_attachments': 'Ask about attachments',
  'dialogue.opt.open_loadout': 'Change loadout',
  'dialogue.opt.ask_balance': 'Ask about weapon balance',
  'dialogue.opt.view_contracts': 'View contracts',
  'dialogue.opt.ask_modes': 'Ask about game modes',
  'dialogue.opt.start_tutorial': 'Start training',
  'dialogue.opt.ask_movement': 'Ask about movement',
  'dialogue.opt.ask_slide': 'Ask about sliding',
  'dialogue.opt.mention_signal': 'Mention the signal',
  'dialogue.opt.ask_more': 'Ask for more',
  'dialogue.opt.accept_chain': 'Accept',
  'dialogue.opt.back': 'Back',
  'dialogue.opt.leave': 'End conversation',

  'tutorial.title': 'Basic Training',
  'tutorial.move': 'Move with WASD',
  'tutorial.look': 'Look around with the mouse',
  'tutorial.jump': 'Jump with Space',
  'tutorial.sprint': 'Sprint with Shift',
  'tutorial.slide': 'Slide with Ctrl while sprinting',
  'tutorial.dash': 'Dash with Q',
  'tutorial.aim': 'Aim with right mouse',
  'tutorial.fire': 'Fire with left mouse',
  'tutorial.reload': 'Reload with R',
  'tutorial.swap': 'Swap weapons with the number keys',
  'tutorial.skill': 'Use your ability with E',
  'tutorial.targets': 'Hit all five targets',
  'tutorial.complete': 'Training complete',
  'tutorial.skip': 'Skip',

  'premium.titan_pass.name': 'Titan Pass',
  'premium.titan_pass.desc':
    'Season premium reward track and a profile badge. No effect on combat performance.',
  'premium.titan_vip.name': 'Titan VIP',
  'premium.titan_vip.desc':
    'Name colour, extra loadout slots, badge. No effect on combat performance.',
  'premium.not_available': 'This build has no payment provider connected.',
  'premium.no_pay_to_win': 'Paid items never affect combat power.',

  'item.skin_weapon_ashfall.name': 'Ashfall',
  'item.skin_weapon_ashfall.desc': 'Soot and ember finish, worn by long service.',
  'item.skin_weapon_ember_line.name': 'Ember Line',
  'item.skin_weapon_ember_line.desc': 'Scarlet lines across a matte black body.',
  'item.skin_weapon_tidewash.name': 'Tidewash',
  'item.skin_weapon_tidewash.desc': 'Deep-water blues with a bright edge.',
  'item.skin_weapon_dune.name': 'Dune',
  'item.skin_weapon_dune.desc': 'Desert operations camouflage.',
  'item.skin_weapon_frostbite.name': 'Frostbite',
  'item.skin_weapon_frostbite.desc': 'A crystalline surface, rimed with frost.',
  'item.skin_weapon_nightbloom.name': 'Nightbloom',
  'item.skin_weapon_nightbloom.desc': 'Magenta patterns that open in the dark.',
  'item.skin_weapon_aurum.name': 'Aurum',
  'item.skin_weapon_aurum.desc': 'Solid gold plating. Fits any weapon.',
  'item.skin_weapon_voidglass.name': 'Voidglass',
  'item.skin_weapon_voidglass.desc': 'Black glass lit from somewhere inside.',
  'item.skin_char_obsidian.name': 'Obsidian',
  'item.skin_char_obsidian.desc': 'Volcanic-glass armour finish.',
  'item.skin_char_ashline.name': 'Ashline',
  'item.skin_char_ashline.desc': 'Ash grey with amber markings.',
  'item.skin_char_titan.name': 'Titan',
  'item.skin_char_titan.desc': 'Top-tier regalia. A faint light follows the wearer.',
  'item.skin_char_surveyor_field.name': 'Field Survey',
  'item.skin_char_surveyor_field.desc': 'Forward reconnaissance kit.',
  'item.skin_char_forge_industrial.name': 'Industrial',
  'item.skin_char_forge_industrial.desc': 'Practical, workwear-derived rig.',
  'item.skin_vehicle_ranger.name': 'Ranger',
  'item.skin_vehicle_ranger.desc': 'Field reconnaissance livery.',
  'item.skin_vehicle_pulse.name': 'Pulse',
  'item.skin_vehicle_pulse.desc': 'Livery with illuminated trim.',
  'item.charm_foundry.name': 'Foundry Stamp',
  'item.charm_foundry.desc': 'A scrap of metal recovered from the smelter.',
  'item.charm_circuit.name': 'Circuit Fragment',
  'item.charm_circuit.desc': 'A board fragment still carrying a signal.',
  'item.emote_salute.name': 'Salute',
  'item.emote_salute.desc': 'A brief, formal salute.',
  'item.emote_taunt.name': 'Taunt',
  'item.emote_taunt.desc': 'A gesture designed to provoke.',
  'item.emote_victory_pose.name': 'Victory Pose',
  'item.emote_victory_pose.desc': 'A celebration for the win.',

  'item.crate_standard.name': 'Standard Supply Crate',
  'item.crate_standard.desc': 'Contains base cosmetics.',
  'item.crate_premium.name': 'Premium Supply Crate',
  'item.crate_premium.desc': 'Improved odds for rare and above.',
  'item.crate_legendary.name': 'Legendary Supply Crate',
  'item.crate_legendary.desc': 'Epic or better, guaranteed.',

  'title.operative': 'Operative',
  'title.operative.desc': 'Reach level 10',
  'title.veteran': 'Veteran',
  'title.veteran.desc': 'Reach level 20',
  'title.specialist': 'Specialist',
  'title.specialist.desc': 'Reach level 40',
  'title.vanguard_elite': 'Elite Vanguard',
  'title.vanguard_elite.desc': 'Reach level 50',
  'title.titan': 'Titan',
  'title.titan.desc': 'Reach max level',
  'title.archivist': 'Archivist',
  'title.archivist.desc': 'Found every secret',

  'quest.daily_eliminations.name': 'Clean Up',
  'quest.daily_eliminations.desc': 'Eliminate enemies in the field.',
  'quest.daily_headhunter.name': 'Precision Work',
  'quest.daily_headhunter.desc': 'Finish with headshots.',
  'quest.daily_rifleman.name': 'Rifleman',
  'quest.daily_rifleman.desc': 'Eliminate with assault rifles.',
  'quest.daily_closequarters.name': 'Close Quarters',
  'quest.daily_closequarters.desc': 'Eliminate with short-range weapons.',
  'quest.daily_marksman.name': 'Marksman',
  'quest.daily_marksman.desc': 'Eliminate from long range.',
  'quest.daily_victor.name': 'Victor',
  'quest.daily_victor.desc': 'Win matches.',
  'quest.daily_operator.name': 'Tactical Use',
  'quest.daily_operator.desc': 'Make use of your ability.',
  'quest.daily_support.name': 'Support Fire',
  'quest.daily_support.desc': 'Help your team.',
  'quest.daily_objective.name': 'Secure the Point',
  'quest.daily_objective.desc': 'Capture objectives.',
  'quest.daily_driver.name': 'Mobile Recon',
  'quest.daily_driver.desc': 'Cover ground by vehicle.',
  'quest.daily_streak.name': 'On a Run',
  'quest.daily_streak.desc': 'String eliminations together without dying.',
  'quest.daily_damage.name': 'Sustained Fire',
  'quest.daily_damage.desc': 'Accumulate damage.',
  'quest.weekly_campaigner.name': 'Weekly Deployment',
  'quest.weekly_campaigner.desc': 'Play matches this week.',
  'quest.weekly_champion.name': 'Weekly Champion',
  'quest.weekly_champion.desc': 'Win matches this week.',
  'quest.weekly_arsenal.name': 'Arsenal',
  'quest.weekly_arsenal.desc': 'Perform with a range of weapons.',
  'quest.weekly_headhunter.name': 'Weekly Precision',
  'quest.weekly_headhunter.desc': 'Accumulate headshots.',
  'quest.weekly_explorer.name': 'Scout',
  'quest.weekly_explorer.desc': 'See every corner of the battlefield.',
  'quest.story_first_steps.name': 'First Steps',
  'quest.story_first_steps.desc': 'Complete your first match.',
  'quest.story_first_blood.name': 'First Contact',
  'quest.story_first_blood.desc': 'Eliminate enemies.',
  'quest.story_quartermaster.name': 'Requisition',
  'quest.story_quartermaster.desc': 'Speak to Quartermaster Ren.',
  'quest.story_specialist.name': 'Tactical Mastery',
  'quest.story_specialist.desc': 'Eliminate enemies with your ability.',
  'quest.story_proving_ground.name': 'Proving Ground',
  'quest.story_proving_ground.desc': 'Win a match.',
  'quest.secret_foundry_vault.name': 'The Sealed Vault',
  'quest.secret_foundry_vault.desc': 'Something is buried under Foundry Reach.',
  'quest.secret_quarter_backroom.name': 'The Locked Back Room',
  'quest.secret_quarter_backroom.desc': 'Behind the shutter at the end of the flooded alley.',
  'quest.secret_hub_signal.name': 'A Faint Signal',
  'quest.secret_hub_signal.desc': 'Something is transmitting inside the hub.',
  'quest.secret_archivist_chain.name': "The Archivist's Request",
  'quest.secret_archivist_chain.desc': 'The Archivist wants the remaining traces found.',

  'ach.first_kill.name': 'First Blood',
  'ach.first_kill.desc': 'Eliminate your first enemy.',
  'ach.first_win.name': 'First Victory',
  'ach.first_win.desc': 'Win your first match.',
  'ach.kills_1.name': 'Practised',
  'ach.kills_1.desc': '100 total eliminations',
  'ach.kills_2.name': 'Expert',
  'ach.kills_2.desc': '1,000 total eliminations',
  'ach.kills_3.name': 'Field Dominant',
  'ach.kills_3.desc': '5,000 total eliminations',
  'ach.streak_10.name': 'Unstoppable',
  'ach.streak_10.desc': 'A 10 kill streak',
  'ach.level_25.name': 'Experienced',
  'ach.level_25.desc': 'Reach level 25',
  'ach.rank_gold.name': 'Gold Tier',
  'ach.rank_gold.desc': 'Reach Gold rank',
  'ach.collector.name': 'Collector',
  'ach.collector.desc': 'Collect 25 items',
  'ach.secret_finder.name': 'Seeker',
  'ach.secret_finder.desc': 'Found every hidden terminal.',
  'ach.ghost_route.name': 'Ghost Route',
  'ach.ghost_route.desc': 'Found a way nobody knows about.',

  'dev.title': 'Developer Tools',
  'dev.disabled': 'Not available in this build.',
  'dev.performance': 'Performance monitor',
  'dev.spawn_test': 'Spawn test',
  'dev.weapon_test': 'Weapon test',
  'dev.damage_test': 'Damage test',
  'dev.economy_test': 'Economy test',
};
