/**
 * 한국어 (Korean) — the project's primary language.
 * Keys are grouped by screen/system. Keep alphabetical within a group.
 */

export const ko: Record<string, string> = {
  // ---------------------------------------------------------------- 공통 --
  'app.title': 'PROJECT TITAN',
  'common.ok': '확인',
  'common.cancel': '취소',
  'common.back': '뒤로',
  'common.close': '닫기',
  'common.confirm': '결정',
  'common.yes': '예',
  'common.no': '아니오',
  'common.loading': '불러오는 중...',
  'common.retry': '다시 시도',
  'common.equip': '장착',
  'common.equipped': '장착됨',
  'common.unequip': '해제',
  'common.buy': '구매',
  'common.owned': '보유 중',
  'common.locked': '잠김',
  'common.level_required': '레벨 {level} 필요',
  'common.free': '무료',
  'common.search': '검색',
  'common.all': '전체',
  'common.none': '없음',
  'common.save': '저장',
  'common.reset': '초기화',
  'common.apply': '적용',
  'common.next': '다음',
  'common.previous': '이전',
  'common.claim': '수령',
  'common.claimed': '수령 완료',
  'common.progress': '진행도',
  'common.complete': '완료',
  'common.seconds': '{count}초',
  'common.minutes': '{count}분',

  // ------------------------------------------------------------- 로딩/부팅 --
  'boot.initializing': '시스템 초기화 중',
  'boot.loading_assets': '에셋 불러오는 중',
  'boot.connecting': '서버 연결 중',
  'boot.loading_profile': '프로필 불러오는 중',
  'boot.building_world': '월드 생성 중',
  'boot.ready': '준비 완료',
  'boot.tip': '팁',

  // ------------------------------------------------------------- 메인 메뉴 --
  'menu.play': '플레이',
  'menu.lobby': '로비',
  'menu.inventory': '인벤토리',
  'menu.shop': '상점',
  'menu.loadout': '장비',
  'menu.characters': '캐릭터',
  'menu.quests': '퀘스트',
  'menu.rank': '랭크',
  'menu.season': '시즌',
  'menu.leaderboard': '리더보드',
  'menu.settings': '설정',
  'menu.profile': '프로필',
  'menu.news': '공지',
  'menu.social': '소셜',
  'menu.quit': '종료',
  'menu.tutorial': '튜토리얼',

  // ------------------------------------------------------------- 로그인 --
  'login.title': '작전 요원 인증',
  'login.name_label': '요원 이름',
  'login.name_placeholder': '이름을 입력하세요',
  'login.enter': '입장',
  'login.guest': '게스트로 시작',
  'login.name_too_short': '이름은 2자 이상이어야 합니다.',
  'login.name_too_long': '이름은 16자 이하여야 합니다.',
  'login.name_invalid': '사용할 수 없는 문자가 포함되어 있습니다.',
  'login.returning': '다시 오신 것을 환영합니다, {name} 요원.',

  // --------------------------------------------------------------- 매치 --
  'match.searching': '매치 검색 중',
  'match.found': '매치를 찾았습니다',
  'match.joining': '입장 중',
  'match.cancel_search': '검색 취소',
  'match.queue_time': '대기 시간 {time}',
  'match.players_found': '{current} / {total} 명',
  'match.warmup': '준비 시간',
  'match.starting_in': '{count}초 후 시작',
  'match.round': '{current} 라운드',
  'match.round_start': '라운드 시작',
  'match.round_end': '라운드 종료',
  'match.victory': '승리',
  'match.defeat': '패배',
  'match.draw': '무승부',
  'match.match_end': '경기 종료',
  'match.overtime': '연장전',
  'match.spectating': '{name} 관전 중',
  'match.respawning': '{count}초 후 리스폰',
  'match.eliminated': '탈락',
  'match.waiting_players': '플레이어를 기다리는 중',
  'match.team_alpha': '알파',
  'match.team_bravo': '브라보',
  'match.score': '점수',
  'match.leave': '경기 나가기',
  'match.leave_confirm': '정말 나가시겠습니까? 진행 중인 보상을 잃을 수 있습니다.',

  // --------------------------------------------------------------- HUD --
  'hud.health': '체력',
  'hud.shield': '보호막',
  'hud.ammo': '탄약',
  'hud.stamina': '스태미나',
  'hud.reloading': '재장전 중',
  'hud.no_ammo': '탄약 없음',
  'hud.skill_ready': '스킬 준비됨',
  'hud.spawn_protection': '스폰 보호',
  'hud.objective_capturing': '점령 중',
  'hud.objective_contested': '교전 중',
  'hud.objective_captured': '{team} 점령',
  'hud.killstreak': '{count} 연속 킬',
  'hud.doublekill': '더블 킬',
  'hud.triplekill': '트리플 킬',
  'hud.multikill': '멀티 킬 x{count}',
  'hud.headshot': '헤드샷',
  'hud.first_blood': '선취점',
  'hud.assist': '어시스트',
  'hud.out_of_bounds': '전장으로 복귀하세요 {count}',
  'hud.interact': '{key} 키로 상호작용',
  'hud.enter_vehicle': '{key} 키로 탑승',
  'hud.exit_vehicle': '{key} 키로 하차',
  'hud.press_to_talk': '{key} 키로 대화',

  // -------------------------------------------------------------- 킬 피드 --
  'killfeed.killed': '처치',
  'killfeed.suicide': '자멸',
  'killfeed.fall': '추락사',
  'killfeed.environment': '환경',
  'killfeed.vehicle': '차량',

  // ------------------------------------------------------------ 결과 화면 --
  'result.title': '경기 결과',
  'result.mvp': '최우수 선수',
  'result.kills': '킬',
  'result.deaths': '데스',
  'result.assists': '어시스트',
  'result.kd': 'K/D',
  'result.damage': '데미지',
  'result.headshots': '헤드샷',
  'result.score': '점수',
  'result.accuracy': '명중률',
  'result.best_streak': '최고 연속 킬',
  'result.xp_earned': '획득 경험치',
  'result.coins_earned': '획득 코인',
  'result.rank_change': '랭크 변동',
  'result.continue': '계속',
  'result.rematch': '다시 하기',
  'result.time_played': '플레이 시간',

  // ------------------------------------------------------------ 인벤토리 --
  'inventory.title': '인벤토리',
  'inventory.category': '분류',
  'inventory.rarity': '희귀도',
  'inventory.sort': '정렬',
  'inventory.sort_rarity': '희귀도순',
  'inventory.sort_name': '이름순',
  'inventory.sort_recent': '최신순',
  'inventory.empty': '해당하는 아이템이 없습니다.',
  'inventory.empty_hint': '상점에서 스킨과 보급 상자를 구매하거나, 임무와 랭크 보상으로 획득할 수 있습니다.',
  'inventory.preview': '미리보기',
  'inventory.item_count': '{count}개 보유',

  // --------------------------------------------------------------- 상점 --
  'shop.title': '상점',
  'shop.section.featured': '추천',
  'shop.section.daily': '일일 상품',
  'shop.section.weapons': '무기',
  'shop.section.attachments': '부착물',
  'shop.section.characters': '캐릭터',
  'shop.section.cosmetics': '꾸미기',
  'shop.section.crates': '보급 상자',
  'shop.section.event': '이벤트',
  'shop.refresh_in': '{time} 후 갱신',
  'shop.purchase_confirm': '{item}을(를) {price} {currency}에 구매하시겠습니까?',
  'shop.purchase_success': '구매 완료: {item}',
  'shop.discount': '{percent}% 할인',
  'shop.balance': '보유 재화',

  // --------------------------------------------------------------- 재화 --
  'currency.coins': '코인',
  'currency.cores': '코어',

  // -------------------------------------------------------------- 보급함 --
  'crate.open': '개봉',
  'crate.opening': '개봉 중',
  'crate.rates_title': '획득 확률',
  'crate.rates_note': '아래 확률은 서버가 실제로 사용하는 값과 동일합니다.',
  'crate.duplicate': '중복 — {coins} 코인으로 전환',
  'crate.pity': '{count}회 내에 {rarity} 등급 이상 확정',
  'crate.result_title': '획득 아이템',

  // -------------------------------------------------------------- 희귀도 --
  'rarity.common': '일반',
  'rarity.uncommon': '고급',
  'rarity.rare': '희귀',
  'rarity.epic': '영웅',
  'rarity.legendary': '전설',
  'rarity.mythic': '신화',

  // -------------------------------------------------------------- 퀘스트 --
  'quest.title': '퀘스트',
  'quest.daily': '일일 퀘스트',
  'quest.weekly': '주간 퀘스트',
  'quest.story': '임무',
  'quest.secret': '비밀',
  'quest.secret_undiscovered': '???',
  'quest.resets_in': '{time} 후 초기화',
  'quest.completed': '완료됨',
  'quest.claim_reward': '보상 수령',
  'quest.new_available': '새로운 퀘스트가 있습니다',
  'quest.progress_updated': '{name} ({current}/{total})',

  'objective.kill': '적 {count}명 처치',
  'objective.kill_class': '{target}(으)로 {count}명 처치',
  'objective.headshot': '헤드샷 {count}회',
  'objective.assist': '어시스트 {count}회',
  'objective.damage': '데미지 {count} 누적',
  'objective.win': '경기 {count}회 승리',
  'objective.play': '경기 {count}회 플레이',
  'objective.capture': '거점 {count}회 점령',
  'objective.use_skill': '스킬 {count}회 사용',
  'objective.skill_kill': '스킬로 {count}명 처치',
  'objective.streak': '{threshold} 연속 킬 달성',
  'objective.long_shot': '{threshold}m 이상 거리에서 {count}회 처치',
  'objective.visit': '특정 구역 발견',
  'objective.talk': '요원과 대화',
  'objective.collect': '아이템 {count}개 수집',
  'objective.level': '레벨 {count} 달성',
  'objective.rank': '{target} 랭크 달성',
  'objective.terminal': '단말기 작동',
  'objective.panel': '숨겨진 패널 발견',
  'objective.find_vault': '봉인된 격납고 진입',
  'objective.find_backroom': '뒷방 진입',
  'objective.vehicle_distance': '차량으로 {count}m 주행',

  // ------------------------------------------------------------ 성장/랭크 --
  'progress.level': '레벨 {level}',
  'progress.level_up': '레벨 업!',
  'progress.xp': '{current} / {total} XP',
  'progress.max_level': '최고 레벨',
  'progress.reward_unlocked': '보상 해금: {name}',
  'rank.title': '랭크',
  'rank.unranked': '배치 전',
  'rank.iron': '아이언',
  'rank.bronze': '브론즈',
  'rank.silver': '실버',
  'rank.gold': '골드',
  'rank.platinum': '플래티넘',
  'rank.diamond': '다이아몬드',
  'rank.ascendant': '어센던트',
  'rank.titan': '타이탄',
  'rank.division': '{tier} {division}',
  'rank.promoted': '승급!',
  'rank.demoted': '강등',
  'rank.points': '{points} RP',
  'rank.placement': '배치 경기 {current}/{total}',

  // -------------------------------------------------------------- 시즌 --
  'season.title': '시즌',
  'season.level': '시즌 레벨 {level}',
  'season.ends_in': '{time} 후 종료',
  'season.premium_locked': '프리미엄 트랙 잠김',
  'season.s1.name': '시즌 1: 첫 신호',
  'season.s1.desc': '타이탄 계획의 첫 번째 작전 시즌입니다.',

  // -------------------------------------------------------------- 출석 --
  'login_reward.title': '출석 보상',
  'login_reward.streak': '{count}일 연속 출석',
  'login_reward.day': '{day}일차',
  'login_reward.today': '오늘의 보상',
  'login_reward.missed': '연속 출석이 초기화되었습니다.',

  // -------------------------------------------------------------- 업적 --
  'achievement.title': '업적',
  'achievement.unlocked': '업적 달성: {name}',
  'achievement.hidden': '숨겨진 업적',
  'achievement.progress': '{current} / {total}',

  // -------------------------------------------------------------- 파티 --
  'party.title': '파티',
  'party.create': '파티 만들기',
  'party.invite': '초대',
  'party.leave': '파티 나가기',
  'party.disband': '파티 해산',
  'party.leader': '파티장',
  'party.ready': '준비',
  'party.not_ready': '준비 안 됨',
  'party.code': '파티 코드: {code}',
  'party.join_code': '코드로 참가',
  'party.full': '파티가 가득 찼습니다.',
  'party.invited': '{name}님을 초대했습니다.',
  'party.joined': '{name}님이 참가했습니다.',
  'party.left': '{name}님이 나갔습니다.',
  'party.member_count': '{current}/{max}명',

  // -------------------------------------------------------------- 소셜 --
  'social.friends': '친구',
  'social.add_friend': '친구 추가',
  'social.remove_friend': '친구 삭제',
  'social.online': '온라인',
  'social.offline': '오프라인',
  'social.in_match': '경기 중',
  'social.in_lobby': '로비',
  'social.block': '차단',
  'social.unblock': '차단 해제',
  'social.mute': '음소거',
  'social.report': '신고',
  'social.blocked_list': '차단 목록',

  // -------------------------------------------------------------- 신고 --
  'report.title': '플레이어 신고',
  'report.reason': '사유',
  'report.reason.cheating': '부정행위',
  'report.reason.abuse': '욕설/폭언',
  'report.reason.exploit': '버그 악용',
  'report.reason.other': '기타',
  'report.details': '추가 설명 (선택)',
  'report.submit': '신고하기',
  'report.submitted': '신고가 접수되었습니다. 검토 후 조치됩니다.',
  'report.privacy_note': '신고에는 검토에 필요한 최소한의 정보만 포함됩니다.',

  // -------------------------------------------------------------- 관전 --
  'spectate.title': '관전',
  'spectate.next': '다음 플레이어',
  'spectate.prev': '이전 플레이어',
  'spectate.free_cam': '자유 시점',
  'spectate.follow': '따라가기',

  // -------------------------------------------------------------- 설정 --
  'settings.title': '설정',
  'settings.tab.graphics': '그래픽',
  'settings.tab.audio': '오디오',
  'settings.tab.controls': '조작',
  'settings.tab.gameplay': '게임플레이',
  'settings.tab.accessibility': '접근성',
  'settings.tab.language': '언어',

  'settings.graphics.preset': '품질 프리셋',
  'settings.graphics.preset.low': '낮음',
  'settings.graphics.preset.medium': '보통',
  'settings.graphics.preset.high': '높음',
  'settings.graphics.preset.custom': '사용자 지정',
  'settings.graphics.resolution_scale': '해상도 배율',
  'settings.graphics.fps_limit': 'FPS 제한',
  'settings.graphics.vsync': '수직 동기화',
  'settings.graphics.shadows': '그림자',
  'settings.graphics.shadow_quality': '그림자 품질',
  'settings.graphics.postprocessing': '후처리',
  'settings.graphics.bloom': '블룸',
  'settings.graphics.vfx_quality': 'VFX 품질',
  'settings.graphics.particle_density': '파티클 밀도',
  'settings.graphics.view_distance': '시야 거리',
  'settings.graphics.anisotropic': '이방성 필터링',
  'settings.graphics.antialiasing': '안티에일리어싱',
  'settings.graphics.detail_props': '세부 오브젝트',
  'settings.graphics.reflections': '반사',
  'settings.graphics.low_spec_note': '낮음 프리셋에서도 적, 탄약, 목표는 항상 명확히 표시됩니다.',

  'settings.audio.master': '전체 볼륨',
  'settings.audio.music': '음악',
  'settings.audio.sfx': '효과음',
  'settings.audio.voice': '음성',
  'settings.audio.ui': 'UI 사운드',
  'settings.audio.ambience': '환경음',
  'settings.audio.spatial': '공간 음향',

  'settings.controls.sensitivity': '마우스 감도',
  'settings.controls.ads_sensitivity': '조준 감도 배율',
  'settings.controls.invert_y': 'Y축 반전',
  'settings.controls.toggle_ads': '조준 토글',
  'settings.controls.toggle_crouch': '앉기 토글',
  'settings.controls.toggle_sprint': '달리기 토글',
  'settings.controls.keybinds': '키 설정',
  'settings.controls.rebind': '{action} 키를 누르세요',
  'settings.controls.gamepad': '게임패드',
  'settings.controls.gamepad_sensitivity': '게임패드 감도',
  'settings.controls.touch_layout': '터치 조작 배치',
  'settings.controls.reset_defaults': '기본값으로 초기화',

  'settings.gameplay.fov': '시야각 (FOV)',
  'settings.gameplay.crosshair': '크로스헤어',
  'settings.gameplay.crosshair_color': '크로스헤어 색상',
  'settings.gameplay.crosshair_size': '크로스헤어 크기',
  'settings.gameplay.crosshair_gap': '크로스헤어 간격',
  'settings.gameplay.crosshair_dot': '중앙 점',
  'settings.gameplay.damage_numbers': '데미지 표시',
  'settings.gameplay.hitmarkers': '히트마커',
  'settings.gameplay.killfeed': '킬 피드',
  'settings.gameplay.minimap_rotate': '미니맵 회전',
  'settings.gameplay.show_fps': 'FPS 표시',
  'settings.gameplay.show_ping': '핑 표시',

  'settings.accessibility.camera_shake': '화면 흔들림',
  'settings.accessibility.motion_reduction': '모션 감소',
  'settings.accessibility.text_size': '텍스트 크기',
  'settings.accessibility.subtitles': '자막',
  'settings.accessibility.subtitle_size': '자막 크기',
  'settings.accessibility.colorblind': '색각 보조',
  'settings.accessibility.colorblind.none': '사용 안 함',
  'settings.accessibility.colorblind.protanopia': '적색약',
  'settings.accessibility.colorblind.deuteranopia': '녹색약',
  'settings.accessibility.colorblind.tritanopia': '청색약',
  'settings.accessibility.high_contrast': '고대비 UI',
  'settings.accessibility.flash_reduction': '섬광 효과 감소',
  'settings.accessibility.hold_to_ads': '조준 유지 방식',
  'settings.accessibility.audio_cues': '시각적 오디오 표시',

  'settings.language.title': '언어',
  'settings.language.planned': '준비 중',
  'locale.ko': '한국어',
  'locale.en': '영어',

  // ----------------------------------------------------------- 서버 상태 --
  'network.ping': '핑 {ms}ms',
  'network.status.excellent': '매우 좋음',
  'network.status.good': '좋음',
  'network.status.fair': '보통',
  'network.status.poor': '나쁨',
  'network.disconnected': '연결이 끊어졌습니다',
  'network.reconnecting': '재연결 중... ({attempt}/{max})',
  'network.reconnected': '다시 연결되었습니다',
  'network.reconnect_failed': '재연결에 실패했습니다.',
  'network.session_restored': '경기 상태를 복구했습니다.',
  'network.server_status': '서버 상태',

  // -------------------------------------------------------------- 알림 --
  'notify.item_received': '{name} 획득',
  'notify.reward_received': '보상 획득',
  'notify.level_up': '레벨 {level} 달성',
  'notify.rank_up': '{rank}(으)로 승급',
  'notify.quest_complete': '퀘스트 완료: {name}',
  'notify.achievement': '업적 달성: {name}',
  'notify.friend_online': '{name}님이 접속했습니다',
  'notify.party_invite': '{name}님이 파티에 초대했습니다',
  'notify.event_started': '이벤트 시작: {name}',
  'notify.system': '공지',

  // -------------------------------------------------------------- 오류 --
  'error.unknown': '알 수 없는 문제가 발생했습니다. 잠시 후 다시 시도해 주세요.',
  'error.validation': '입력한 내용을 확인해 주세요.',
  'error.not_found': '요청한 항목을 찾을 수 없습니다.',
  'error.forbidden': '권한이 없습니다.',
  'error.rate_limited': '요청이 너무 잦습니다. 잠시 후 다시 시도해 주세요.',
  'error.insufficient_funds': '재화가 부족합니다.',
  'error.already_owned': '이미 보유한 아이템입니다.',
  'error.not_owned': '보유하지 않은 아이템입니다.',
  'error.level_requirement': '레벨 {level} 이상이어야 합니다.',
  'error.unavailable': '현재 이용할 수 없습니다.',
  'error.conflict': '다른 곳에서 변경되었습니다. 새로고침 후 다시 시도해 주세요.',
  'error.storage': '저장에 실패했습니다. 진행 상황은 임시 보관되었습니다.',
  'error.network': '네트워크에 연결할 수 없습니다.',
  'error.match_full': '경기가 가득 찼습니다.',
  'error.party_full': '파티가 가득 찼습니다.',
  'error.not_party_leader': '파티장만 할 수 있습니다.',
  'error.asset_missing': '리소스를 불러오지 못했습니다. 기본 리소스로 대체합니다.',
  'error.payment_unavailable': '이 빌드에는 결제 기능이 포함되어 있지 않습니다.',
  'error.protocol_mismatch': '클라이언트 버전이 서버와 다릅니다. 새로고침해 주세요.',

  // -------------------------------------------------------------- 무기 --
  'weapon.tr9_sentinel.name': 'TR-9 센티넬',
  'weapon.tr9_sentinel.desc': '균형 잡힌 표준 돌격소총. 중거리에서 가장 안정적입니다.',
  'weapon.ak_ridgeline.name': 'AK 리지라인',
  'weapon.ak_ridgeline.desc': '높은 위력과 강한 반동. 짧은 점사에 능숙해야 합니다.',
  'weapon.vx3_lattice.name': 'VX-3 래티스',
  'weapon.vx3_lattice.desc': '3점사 정밀 소총. 한 번의 실수가 크게 돌아옵니다.',
  'weapon.vp4_hornet.name': 'VP-4 호넷',
  'weapon.vp4_hornet.desc': '최상급 근접 화력. 30m를 넘기면 급격히 약해집니다.',
  'weapon.sk2_cinder.name': 'SK-2 신더',
  'weapon.sk2_cinder.desc': '통제하기 쉬운 기관단총. 탄창이 작습니다.',
  'weapon.br12_fracture.name': 'BR-12 프랙처',
  'weapon.br12_fracture.desc': '초근접 한 방. 개활지에서는 무력합니다.',
  'weapon.mk7_nightfall.name': 'MK-7 나이트폴',
  'weapon.mk7_nightfall.desc': '거리 무관 헤드샷 즉사. 접근당하면 대응이 어렵습니다.',
  'weapon.dm3_verdict.name': 'DM-3 버딕트',
  'weapon.dm3_verdict.desc': '반자동 지정사수 소총. 두 발이면 충분합니다.',
  'weapon.sp1_ember.name': 'SP-1 엠버',
  'weapon.sp1_ember.desc': '가장 빠른 교체 속도. 위기 상황의 마지막 수단.',
  'weapon.rift_blade.name': '리프트 블레이드',
  'weapon.rift_blade.desc': '최고의 이동 속도와 2회 타격 처치. 접근이 전부입니다.',
  'weapon.arc9_tempest.name': 'ARC-9 템페스트',
  'weapon.arc9_tempest.desc': '감쇠 없는 에너지 폭발탄. 느린 탄속을 예측해야 합니다.',

  'weapon.class.assault_rifle': '돌격소총',
  'weapon.class.smg': '기관단총',
  'weapon.class.shotgun': '산탄총',
  'weapon.class.sniper': '저격소총',
  'weapon.class.marksman': '지정사수소총',
  'weapon.class.pistol': '권총',
  'weapon.class.melee': '근접',
  'weapon.class.special': '특수',

  'weapon.stat.damage': '데미지',
  'weapon.stat.fire_rate': '연사 속도',
  'weapon.stat.range': '사거리',
  'weapon.stat.accuracy': '정확도',
  'weapon.stat.recoil': '반동 제어',
  'weapon.stat.mobility': '기동성',
  'weapon.stat.magazine': '탄창',
  'weapon.stat.reload': '재장전',
  'weapon.stat.ads_speed': '조준 속도',
  'weapon.stat.headshot': '헤드샷 배율',

  // ------------------------------------------------------------ 부착물 --
  'attachment.slot.optic': '조준기',
  'attachment.slot.barrel': '총열',
  'attachment.slot.grip': '손잡이',
  'attachment.slot.magazine': '탄창',
  'attachment.slot.stock': '개머리판',
  'attachment.slot.special': '특수',
  'attachment.optic_reflex.name': '리플렉스 조준경',
  'attachment.optic_reflex.desc': '시야가 깔끔해지지만 조준 속도가 조금 느려집니다.',
  'attachment.optic_longscope.name': '장거리 조준경',
  'attachment.optic_longscope.desc': '강한 확대. 조준 속도와 기동성을 희생합니다.',
  'attachment.optic_holo_wide.name': '광각 홀로그램',
  'attachment.optic_holo_wide.desc': '빠른 조준과 넓은 시야. 탄퍼짐이 늘어납니다.',
  'attachment.barrel_long.name': '연장 총열',
  'attachment.barrel_long.desc': '유효 사거리 증가. 무거워집니다.',
  'attachment.barrel_suppressor.name': '소음기',
  'attachment.barrel_suppressor.desc': '발사해도 미니맵에 노출되지 않습니다. 위력과 사거리가 줄어듭니다.',
  'attachment.barrel_compensator.name': '컴펜세이터',
  'attachment.barrel_compensator.desc': '수직 반동 감소, 수평 반동 증가.',
  'attachment.grip_vertical.name': '수직 손잡이',
  'attachment.grip_vertical.desc': '반동 제어 향상. 조준 이동 속도 감소.',
  'attachment.grip_light.name': '경량 손잡이',
  'attachment.grip_light.desc': '빠른 조준과 기동성. 수평 반동이 커집니다.',
  'attachment.mag_extended.name': '확장 탄창',
  'attachment.mag_extended.desc': '장탄수 +10. 재장전이 느려집니다.',
  'attachment.mag_quickdraw.name': '속사 탄창',
  'attachment.mag_quickdraw.desc': '재장전 대폭 단축. 장탄수 -4.',
  'attachment.stock_heavy.name': '중량 개머리판',
  'attachment.stock_heavy.desc': '안정성 향상. 이동 속도 감소.',
  'attachment.stock_skeletal.name': '경량 개머리판',
  'attachment.stock_skeletal.desc': '이동성 향상. 반동 제어가 어려워집니다.',
  'attachment.special_ported_chamber.name': '포팅 챔버',
  'attachment.special_ported_chamber.desc': '연사 속도 증가, 발당 데미지 감소.',
  'attachment.special_focus_coil.name': '포커스 코일',
  'attachment.special_focus_coil.desc': '탄퍼짐 대폭 감소. 무기 전환이 느려집니다.',

  // ------------------------------------------------------------ 캐릭터 --
  'character.vanguard.name': '뱅가드',
  'character.vanguard.desc': '모든 수치가 기준치인 만능형 요원입니다.',
  'character.specter.name': '스펙터',
  'character.specter.desc': '빠르지만 약합니다. 측면 침투에 특화되어 있습니다.',
  'character.warden.name': '워든',
  'character.warden.desc': '보호막이 두껍고 느립니다. 거점 사수형입니다.',
  'character.surveyor.name': '서베이어',
  'character.surveyor.desc': '정보 수집형. 능력으로 팀을 이끕니다.',
  'character.forge.name': '포지',
  'character.forge.desc': '지원형. 아군을 회복시킵니다.',

  // -------------------------------------------------------------- 스킬 --
  'skill.pulse_dash.name': '펄스 대시',
  'skill.pulse_dash.desc': '짧은 거리를 순간적으로 돌파합니다. 대시 중에는 방향을 바꿀 수 없습니다.',
  'skill.pulse_dash.up1': '재사용 대기시간 10% 감소',
  'skill.pulse_dash.up2': '추진력 10% 증가',
  'skill.bulwark.name': '벌워크',
  'skill.bulwark.desc': '전개형 방벽을 설치합니다. 아군의 사격도 막습니다.',
  'skill.bulwark.up1': '방벽 내구도 15% 증가',
  'skill.bulwark.up2': '지속 시간 20% 증가',
  'skill.scan_pulse.name': '스캔 펄스',
  'skill.scan_pulse.desc': '주변의 적을 잠시 노출시킵니다. 소리로 위치가 드러납니다.',
  'skill.scan_pulse.up1': '범위 15% 증가',
  'skill.scan_pulse.up2': '재사용 대기시간 15% 감소',
  'skill.ion_charge.name': '이온 차지',
  'skill.ion_charge.desc': '폭발 장약을 투척합니다. 단독으로는 처치할 수 없습니다.',
  'skill.ion_charge.up1': '폭발 범위 12% 증가',
  'skill.ion_charge.up2': '기폭 시간 20% 단축',
  'skill.phase_veil.name': '페이즈 베일',
  'skill.phase_veil.desc': '모습을 흐립니다. 사용 중에는 사격할 수 없습니다.',
  'skill.phase_veil.up1': '지속 시간 15% 증가',
  'skill.phase_veil.up2': '은신 효과 강화',
  'skill.field_repair.name': '필드 리페어',
  'skill.field_repair.desc': '자신과 주변 아군을 회복합니다. 피격 시 중단됩니다.',
  'skill.field_repair.up1': '회복량 15% 증가',
  'skill.field_repair.up2': '범위 20% 증가',
  'skill.category.offense': '공격',
  'skill.category.defense': '방어',
  'skill.category.mobility': '이동',
  'skill.category.utility': '지원',

  // -------------------------------------------------------------- 차량 --
  'vehicle.scout_buggy.name': '스카우트 버기',
  'vehicle.scout_buggy.desc': '빠르고 약한 정찰 차량. 엔진 소리가 멀리까지 들립니다.',

  // --------------------------------------------------------------- 맵 --
  'map.foundry_reach.name': '파운드리 리치',
  'map.foundry_reach.desc': '해질녘의 제련 단지. 서쪽 장거리, 중앙 입체 전투, 동쪽 근접전.',
  'map.foundry_reach.obj.yard': '적재장',
  'map.foundry_reach.obj.foundry': '제련소',
  'map.foundry_reach.obj.depot': '창고',
  'map.neon_quarter.name': '네온 쿼터',
  'map.neon_quarter.desc': '비 내리는 야간 상점가. 광장을 건널 것인가, 돌아갈 것인가.',
  'map.neon_quarter.obj.plaza': '중앙 광장',
  'map.neon_quarter.obj.west_row': '서편 상가',
  'map.neon_quarter.obj.east_row': '동편 상가',
  'map.titan_hub.name': '타이탄 허브',
  'map.titan_hub.desc': '작전 대기 구역.',
  'map.zone.west_yard': '서쪽 적재장',
  'map.zone.foundry_hall': '제련 홀',
  'map.zone.east_warehouse': '동쪽 창고',
  'map.zone.rooftops': '옥상',
  'map.zone.tunnel': '정비 터널',
  'map.zone.vault': '봉인 격납고',
  'map.zone.plaza': '광장',
  'map.zone.walkway': '고가 통로',
  'map.zone.shops_west': '서편 상가',
  'map.zone.shops_east': '동편 상가',
  'map.zone.alley': '침수 골목',
  'map.zone.backroom': '뒷방',
  'map.zone.concourse': '중앙 홀',
  'map.zone.range': '사격장',
  'map.zone.mezzanine': '중층',

  // -------------------------------------------------------------- 모드 --
  'mode.tdm.name': '팀 데스매치',
  'mode.tdm.desc': '먼저 목표 점수에 도달한 팀이 승리합니다.',
  'mode.ffa.name': '개인전',
  'mode.ffa.desc': '모두가 적입니다.',
  'mode.objective.name': '거점 점령',
  'mode.objective.desc': '거점을 점령하고 지켜 점수를 쌓습니다.',
  'mode.elimination.name': '섬멸전',
  'mode.elimination.desc': '리스폰 없음. 라운드마다 마지막까지 살아남으세요.',
  'mode.ranked.name': '랭크전',
  'mode.ranked.desc': '랭크 점수를 걸고 겨룹니다.',

  // -------------------------------------------------------------- NPC --
  'npc.quartermaster.name': '보급관 렌',
  'npc.quartermaster.role': '보급',
  'npc.armorer.name': '정비사 카일',
  'npc.armorer.role': '장비 정비',
  'npc.dispatcher.name': '관제관 이서',
  'npc.dispatcher.role': '작전 배정',
  'npc.instructor.name': '교관 도하',
  'npc.instructor.role': '훈련',
  'npc.archivist.name': '기록관',
  'npc.archivist.role': '???',

  'dialogue.quartermaster.root': '필요한 게 있나, 요원? 재고는 넉넉하다.',
  'dialogue.quartermaster.gear': '좋은 장비보다 중요한 건 상황에 맞는 장비다.',
  'dialogue.quartermaster.attachments': '부착물엔 공짜가 없어. 얻는 게 있으면 잃는 것도 있지.',
  'dialogue.armorer.root': '무기 손질은 내가 맡지. 뭘 들고 나갈 건가?',
  'dialogue.armorer.balance': '어떤 무기든 약점이 있다. 그걸 아는 게 실력이야.',
  'dialogue.dispatcher.root': '작전 목록이 갱신됐다. 확인해 봐.',
  'dialogue.dispatcher.modes': '섬멸전은 한 번 죽으면 끝이다. 신중하게.',
  'dialogue.instructor.root': '기초부터 다시 가자. 몸이 기억할 때까지.',
  'dialogue.instructor.movement': '달리다 앉으면 슬라이딩이다. 코너를 돌 때 써.',
  'dialogue.instructor.slide': '슬라이딩 직후 점프하면 거리를 더 벌 수 있다.',
  'dialogue.archivist.root': '...',
  'dialogue.archivist.signal': '그 신호를 찾았군. 대부분은 평생 모르고 지나가지.',
  'dialogue.archivist.more': '봉인된 곳이 두 군데 더 있다. 찾아낸다면, 다시 오게.',

  'dialogue.opt.browse_shop': '상점을 보여줘',
  'dialogue.opt.ask_about_gear': '장비에 대해 묻기',
  'dialogue.opt.ask_attachments': '부착물에 대해 묻기',
  'dialogue.opt.open_loadout': '장비 변경',
  'dialogue.opt.ask_balance': '무기 밸런스에 대해 묻기',
  'dialogue.opt.view_contracts': '작전 목록 보기',
  'dialogue.opt.ask_modes': '게임 모드에 대해 묻기',
  'dialogue.opt.start_tutorial': '훈련 시작',
  'dialogue.opt.ask_movement': '이동에 대해 묻기',
  'dialogue.opt.ask_slide': '슬라이딩에 대해 묻기',
  'dialogue.opt.mention_signal': '신호에 대해 말한다',
  'dialogue.opt.ask_more': '더 묻는다',
  'dialogue.opt.accept_chain': '수락한다',
  'dialogue.opt.back': '이전',
  'dialogue.opt.leave': '대화 종료',

  // ------------------------------------------------------------ 튜토리얼 --
  'tutorial.title': '기본 훈련',
  'tutorial.move': 'WASD로 이동하세요',
  'tutorial.look': '마우스로 시점을 돌리세요',
  'tutorial.jump': 'Space로 점프하세요',
  'tutorial.sprint': 'Shift로 달리세요',
  'tutorial.slide': '달리는 중 Ctrl로 슬라이딩하세요',
  'tutorial.dash': 'Q로 대시하세요',
  'tutorial.aim': '우클릭으로 조준하세요',
  'tutorial.fire': '좌클릭으로 사격하세요',
  'tutorial.reload': 'R로 재장전하세요',
  'tutorial.swap': '숫자키로 무기를 교체하세요',
  'tutorial.skill': 'E로 스킬을 사용하세요',
  'tutorial.targets': '표적 5개를 모두 맞히세요',
  'tutorial.complete': '훈련 완료',
  'tutorial.skip': '건너뛰기',

  // -------------------------------------------------------------- 프리미엄 --
  'premium.titan_pass.name': '타이탄 패스',
  'premium.titan_pass.desc': '시즌 프리미엄 보상 트랙과 프로필 배지. 전투 성능에는 영향이 없습니다.',
  'premium.titan_vip.name': '타이탄 VIP',
  'premium.titan_vip.desc': '이름 색상, 추가 장비 프리셋 슬롯, 배지. 전투 성능에는 영향이 없습니다.',
  'premium.not_available': '이 빌드에는 결제 기능이 연결되어 있지 않습니다.',
  'premium.no_pay_to_win': '유료 상품은 전투력에 영향을 주지 않습니다.',

  // ---------------------------------------------------------- 스킨/꾸미기 --
  'item.skin_weapon_ashfall.name': '애시폴',
  'item.skin_weapon_ashfall.desc': '재와 불티가 내려앉은 도장. 오랜 실전의 흔적이 남아 있습니다.',
  'item.skin_weapon_ember_line.name': '엠버 라인',
  'item.skin_weapon_ember_line.desc': '검은 본체에 주홍색 선이 흐릅니다.',
  'item.skin_weapon_tidewash.name': '타이드워시',
  'item.skin_weapon_tidewash.desc': '심해의 푸른빛을 입힌 도장.',
  'item.skin_weapon_dune.name': '듄',
  'item.skin_weapon_dune.desc': '사막 작전용 위장 도장.',
  'item.skin_weapon_frostbite.name': '프로스트바이트',
  'item.skin_weapon_frostbite.desc': '서리가 맺힌 듯한 결정 표면.',
  'item.skin_weapon_nightbloom.name': '나이트블룸',
  'item.skin_weapon_nightbloom.desc': '어둠 속에서 피어나는 자홍빛 문양.',
  'item.skin_weapon_aurum.name': '아우룸',
  'item.skin_weapon_aurum.desc': '순금 도금. 모든 무기에 적용할 수 있습니다.',
  'item.skin_weapon_voidglass.name': '보이드글래스',
  'item.skin_weapon_voidglass.desc': '내부에서 빛나는 검은 유리 구조체.',
  'item.skin_char_obsidian.name': '옵시디언',
  'item.skin_char_obsidian.desc': '흑요석 장갑 도장.',
  'item.skin_char_ashline.name': '애시라인',
  'item.skin_char_ashline.desc': '잿빛 바탕에 황색 표식.',
  'item.skin_char_titan.name': '타이탄',
  'item.skin_char_titan.desc': '최고 등급 의장. 착용자 주변에 미세한 빛이 감돕니다.',
  'item.skin_char_surveyor_field.name': '필드 서베이',
  'item.skin_char_surveyor_field.desc': '야전 정찰 장비 사양.',
  'item.skin_char_forge_industrial.name': '인더스트리얼',
  'item.skin_char_forge_industrial.desc': '작업복 기반의 실용적인 사양.',
  'item.skin_vehicle_ranger.name': '레인저',
  'item.skin_vehicle_ranger.desc': '야전 정찰 차량 도장.',
  'item.skin_vehicle_pulse.name': '펄스',
  'item.skin_vehicle_pulse.desc': '발광 라인이 들어간 차량 도장.',
  'item.charm_foundry.name': '파운드리 각인',
  'item.charm_foundry.desc': '제련소에서 회수한 금속 조각.',
  'item.charm_circuit.name': '회로 조각',
  'item.charm_circuit.desc': '아직 신호가 흐르는 기판 조각.',
  'item.emote_salute.name': '경례',
  'item.emote_salute.desc': '간결한 경례 동작.',
  'item.emote_taunt.name': '도발',
  'item.emote_taunt.desc': '상대를 자극하는 동작.',
  'item.emote_victory_pose.name': '승리 포즈',
  'item.emote_victory_pose.desc': '승리를 자축하는 동작.',

  // -------------------------------------------------------------- 아이템 --
  'item.crate_standard.name': '표준 보급 상자',
  'item.crate_standard.desc': '기본 꾸미기 아이템이 들어 있습니다.',
  'item.crate_premium.name': '고급 보급 상자',
  'item.crate_premium.desc': '희귀 이상 확률이 높습니다.',
  'item.crate_legendary.name': '전설 보급 상자',
  'item.crate_legendary.desc': '영웅 등급 이상만 나옵니다.',

  // -------------------------------------------------------------- 칭호 --
  'title.operative': '요원',
  'title.operative.desc': '레벨 10 달성',
  'title.veteran': '베테랑',
  'title.veteran.desc': '레벨 20 달성',
  'title.specialist': '스페셜리스트',
  'title.specialist.desc': '레벨 40 달성',
  'title.vanguard_elite': '정예 뱅가드',
  'title.vanguard_elite.desc': '레벨 50 달성',
  'title.titan': '타이탄',
  'title.titan.desc': '최고 레벨 달성',
  'title.archivist': '기록자',
  'title.archivist.desc': '모든 비밀을 찾아낸 자',

  // -------------------------------------------------------------- 퀘스트명 --
  'quest.daily_eliminations.name': '정리 작업',
  'quest.daily_eliminations.desc': '전장에서 적을 제거하세요.',
  'quest.daily_headhunter.name': '정밀 사격',
  'quest.daily_headhunter.desc': '헤드샷으로 처리하세요.',
  'quest.daily_rifleman.name': '소총수',
  'quest.daily_rifleman.desc': '돌격소총으로 처치하세요.',
  'quest.daily_closequarters.name': '근접 소탕',
  'quest.daily_closequarters.desc': '근거리 무기로 처치하세요.',
  'quest.daily_marksman.name': '장거리 사수',
  'quest.daily_marksman.desc': '먼 거리에서 처치하세요.',
  'quest.daily_victor.name': '승자',
  'quest.daily_victor.desc': '경기에서 승리하세요.',
  'quest.daily_operator.name': '전술 운용',
  'quest.daily_operator.desc': '스킬을 활용하세요.',
  'quest.daily_support.name': '지원 사격',
  'quest.daily_support.desc': '팀을 도우세요.',
  'quest.daily_objective.name': '거점 확보',
  'quest.daily_objective.desc': '거점을 점령하세요.',
  'quest.daily_driver.name': '기동 정찰',
  'quest.daily_driver.desc': '차량으로 이동하세요.',
  'quest.daily_streak.name': '연속 처치',
  'quest.daily_streak.desc': '죽지 않고 연속으로 처치하세요.',
  'quest.daily_damage.name': '화력 투사',
  'quest.daily_damage.desc': '누적 데미지를 기록하세요.',
  'quest.weekly_campaigner.name': '주간 작전',
  'quest.weekly_campaigner.desc': '이번 주 여러 경기에 참여하세요.',
  'quest.weekly_champion.name': '주간 승자',
  'quest.weekly_champion.desc': '이번 주 여러 경기에서 승리하세요.',
  'quest.weekly_arsenal.name': '병기고',
  'quest.weekly_arsenal.desc': '다양한 무기로 실적을 올리세요.',
  'quest.weekly_headhunter.name': '주간 정밀 사격',
  'quest.weekly_headhunter.desc': '헤드샷을 누적하세요.',
  'quest.weekly_explorer.name': '정찰병',
  'quest.weekly_explorer.desc': '전장의 구석구석을 확인하세요.',
  'quest.story_first_steps.name': '첫 걸음',
  'quest.story_first_steps.desc': '첫 경기를 완료하세요.',
  'quest.story_first_blood.name': '첫 교전',
  'quest.story_first_blood.desc': '적을 처치하세요.',
  'quest.story_quartermaster.name': '보급 신청',
  'quest.story_quartermaster.desc': '보급관 렌과 대화하세요.',
  'quest.story_specialist.name': '전술 숙련',
  'quest.story_specialist.desc': '스킬로 적을 처치하세요.',
  'quest.story_proving_ground.name': '실전 증명',
  'quest.story_proving_ground.desc': '경기에서 승리하세요.',
  'quest.secret_foundry_vault.name': '봉인된 격납고',
  'quest.secret_foundry_vault.desc': '파운드리 리치 지하에 무언가가 있습니다.',
  'quest.secret_quarter_backroom.name': '잠긴 뒷방',
  'quest.secret_quarter_backroom.desc': '침수된 골목 끝, 셔터 너머.',
  'quest.secret_hub_signal.name': '희미한 신호',
  'quest.secret_hub_signal.desc': '허브 어딘가에서 신호가 잡힙니다.',
  'quest.secret_archivist_chain.name': '기록자의 의뢰',
  'quest.secret_archivist_chain.desc': '기록관이 남은 흔적을 찾아달라고 합니다.',

  // -------------------------------------------------------------- 업적명 --
  'ach.first_kill.name': '첫 처치',
  'ach.first_kill.desc': '첫 적을 처치했습니다.',
  'ach.first_win.name': '첫 승리',
  'ach.first_win.desc': '첫 경기에서 승리했습니다.',
  'ach.kills_1.name': '숙련자',
  'ach.kills_1.desc': '누적 100킬',
  'ach.kills_2.name': '전문가',
  'ach.kills_2.desc': '누적 1,000킬',
  'ach.kills_3.name': '전장의 지배자',
  'ach.kills_3.desc': '누적 5,000킬',
  'ach.streak_10.name': '무쌍',
  'ach.streak_10.desc': '10연속 처치',
  'ach.level_25.name': '경력자',
  'ach.level_25.desc': '레벨 25 달성',
  'ach.rank_gold.name': '골드 등급',
  'ach.rank_gold.desc': '골드 랭크 달성',
  'ach.collector.name': '수집가',
  'ach.collector.desc': '아이템 25종 수집',
  'ach.secret_finder.name': '탐색자',
  'ach.secret_finder.desc': '숨겨진 단말기를 모두 찾았습니다.',
  'ach.ghost_route.name': '유령 통로',
  'ach.ghost_route.desc': '아무도 모르는 길을 찾았습니다.',

  // ----------------------------------------------------------- 개발자 도구 --
  'dev.title': '개발자 도구',
  'dev.disabled': '이 빌드에서는 사용할 수 없습니다.',
  'dev.performance': '성능 모니터',
  'dev.spawn_test': '스폰 테스트',
  'dev.weapon_test': '무기 테스트',
  'dev.damage_test': '데미지 테스트',
  'dev.economy_test': '경제 테스트',
};
